book_list: 
 - https://fr.calameo.com/read/00052614325d97ee7ae8e

svg_quality: False

headers:
  Upgrade-Insecure-Requests: '1'
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
