book_list: 
 - https://fr.calameo.com/read/YourBookPath_1
 - https://fr.calameo.com/read/YourBookPath_2
 - #etc..

# SVG Quality is cleaner and alows copy-paste but is  
# also slower. If set to false, simple pictures will
# be downloaded
svg_quality: True

# Headers for sending requests
headers:
  Upgrade-Insecure-Requests:  '1'
  User-Agent: # See https://www.whatsmyua.info/
